matrix:
- name: Markdown
  aspell:
    lang: en
    encoding: utf-8
    dictionary: en-GB
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'